spring:
  cloud:
    function:
      definition: paymentProcessor
    stream:
      kafka:
        bindings:
          paymentProcessor-in-0:
            consumer:
              start-offset: earliest
      bindings:
        paymentProcessor-in-0:
          destination: order-event
          group: payment-proc-group
        paymentProcessor-out-0:
          destination: payment-event

server:
  port: 8082