spring:
  cloud:
    function:
      definition: orderPublisher;paymentEventConsumer
    stream:
      bindings:
        orderPublisher-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event

server:
  port: 8081
